language: rust
rust:
- 1.15.0
- stable
- beta
- nightly
cache: cargo
addons:
  apt:
    packages:
    - gcc-arm-linux-gnueabihf
    - libc6-dev-armhf-cross
    - libpulse-dev
    - portaudio19-dev
before_script:
- mkdir pi-tools
- curl -L https://github.com/raspberrypi/tools/archive/648a6eeb1e3c2b40af4eb34d88941ee0edeb3e9a.tar.gz
  | tar xz --strip-components 1 -C pi-tools
- export PATH=$PWD/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/:$PATH
- echo -e '#!/bin/bash' > pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/gcc-sysroot
- echo -e "arm-linux-gnueabihf-gcc --sysroot $PWD/pi-tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot
  \"\$@\"" >> pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/gcc-sysroot
- chmod +x pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/gcc-sysroot
- curl -OL http://mirrordirector.raspbian.org/raspbian/pool/main/a/alsa-lib/libasound2_1.0.25-4_armhf.deb
- ar p libasound2_1.0.25-4_armhf.deb data.tar.gz | tar -xz -C pi-tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot
- curl -OL http://mirrordirector.raspbian.org/raspbian/pool/main/a/alsa-lib/libasound2-dev_1.0.25-4_armhf.deb
- ar p libasound2-dev_1.0.25-4_armhf.deb data.tar.gz | tar -xz -C pi-tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot/
- ln -s ld-linux.so.3 pi-tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot/lib/ld-linux-armhf.so.3
- mkdir -p ~/.cargo
- echo -e '[target.arm-unknown-linux-gnueabihf]\nlinker = "gcc-sysroot"' > ~/.cargo/config
- rustup target add arm-unknown-linux-gnueabihf
script:
- cargo build --no-default-features
- cargo build --no-default-features --features "with-tremor"
- cargo build --no-default-features --features "portaudio-backend"
- cargo build --no-default-features --features "pulseaudio-backend"
- cargo build --no-default-features --features "alsa-backend"
- cargo build --no-default-features --features "alsa-backend" --target arm-unknown-linux-gnueabihf
  --release
before_deploy: zip -j librespot-linux-armhf-raspberry_pi.zip target/arm-unknown-linux-gnueabihf/release/librespot
deploy:
  provider: releases
  api_key:
    secure: Y6q4F2zyVpfZUTkvMjehx5gXP8QidLX7XEwhFRQwZKyC4H0DwmB76yzXn2oPIHqLhsWvXzljFa80+WL7c5MG2baJ/T3vGZ+VfP9Rgy+B0942hfy5GapGdSPyif9hPgRvjKkTwEg7TqDvR6yo9Tc4P1+YqNrW6lDhQFku0M3xDWmNViAHIL/f+UeBSkvbfWf5SoMWsox9FuUEXOXNs2js8IDuQfAPm05UnglQh8YGIyYWddD/cNfJfS40/pVnkdopEirm/sbvX08YhHr9Ktam/FjhESuICi3Pb17bIY+uR4PSzSLWolnPtKr1E28hhJwSncsoJnyFa81BG6nT99bsLCsLXqmtEqnLBIUfH7viyFRFU8kpMr7+muVXF/frAfKjQynJC0QbRJALY8lV5xjthpvaHglb5tHPTdW6ZJLEcqXLkFMQq1sTheBYSW5WpSdsAkgeNsFFhGxs4T0yAhBjAWgDzr1vtvnoZGtza9dNGUA7oJp+OrCO462gMswOzcDZ9ZG5ZeEGjn4cyW/LRbEiv7eq3d6S8c2Wkv6CWqATMPAuwAR3rMGMShN0Rv5uTOs2gEEPl33pKlHnlb7zicQEfLRkxsz39zHPL2+bqFNy7F95erB8BiB7SShjqF2C6/JpUEljp0EDgzkErD6WlkE1NEtcorEH2Z/ABqY7+nei/Qs=
  file: "librespot-linux-armhf-raspberry_pi.zip"
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = stable
notifications:
  email: false
